#!/usr/bin/env python
"""Writes `frontend/src/types/vocab.generated.ts` from `kraft.vocab`. `just vocab`.

`tests/test_vocab_generated.py` asserts the committed file equals `render()`,
the same generate-and-commit shape as `dev/gen_theme.py`. Groups are tuples in
enum order, so the output is byte-stable. `admits_status` and `Verb` are
deliberately not exported: a UI keeps reading `display_status` and the
server's refusals, not offering doors from the status matrix.
"""

from __future__ import annotations

import dataclasses
import json
import sys
from enum import Enum
from pathlib import Path

from kraft import vocab

OUT = Path(__file__).resolve().parents[1] / "frontend" / "src" / "types" / "vocab.generated.ts"
SKIP_FIELDS = {"admits_status"}


def _lit(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    return json.dumps(str(v))


def _enum(const: str, type_name: str, enum: type[Enum]) -> str:
    items = ", ".join(json.dumps(m.value) for m in enum)
    return (
        f"export const {const} = [{items}] as const;\n"
        f"export type {type_name} = (typeof {const})[number];\n"
    )


def _group(const: str, type_name: str, members) -> str:
    items = ", ".join(json.dumps(str(m)) for m in members)
    return f"export const {const}: readonly {type_name}[] = [{items}];\n"


def _traits(const: str, key_type: str, rows, types: dict[str, str]) -> str:
    sample = next(iter(rows.values()))
    fields = [f for f in dataclasses.fields(sample) if f.name not in SKIP_FIELDS]
    shape = "; ".join(f"{f.name}: {types.get(f.name, 'boolean')}" for f in fields)
    out = [f"export const {const}: Record<{key_type}, {{ {shape} }}> = {{"]
    for member, row in rows.items():
        vals = ", ".join(f"{f.name}: {_lit(getattr(row, f.name))}" for f in fields)
        out.append(f"  {json.dumps(member.value)}: {{ {vals} }},")
    out.append("};\n")
    return "\n".join(out)


def render() -> str:
    parts = [
        "// Generated by dev/gen_vocab.py from kraft.vocab. Do not edit: run `just vocab`.\n",
        _enum("DISPLAY_STATUSES", "DisplayStatus", vocab.DisplayStatus),
        _enum("STOP_KINDS", "StopKind", vocab.StopKind),
        _group("FAILURE_STOP_KINDS", "StopKind", vocab.FAILURE_KINDS),
        _traits("STOP_TRAITS", "StopKind", vocab.STOP_TRAITS, {"status": "string"}),
        _enum("WORK_ITEM_STATUSES", "WorkItemStatus", vocab.WorkItemStatus),
        _group("ENDED_STATUSES", "WorkItemStatus", vocab.ENDED),
        _group("STOPPED_STATUSES", "WorkItemStatus", vocab.STOPPED),
        _group("HOLDS_SLOT_STATUSES", "WorkItemStatus", vocab.HOLDS_SLOT),
        _group("RUNNING_STATUSES", "WorkItemStatus", vocab.RUNNING),
        _group("COMMANDS_MAY_START_STATUSES", "WorkItemStatus", vocab.COMMANDS_MAY_START),
        _group("MR_WATCHED_STATUSES", "WorkItemStatus", vocab.MR_WATCHED),
        _traits(
            "WORK_ITEM_TRAITS",
            "WorkItemStatus",
            vocab.TRAITS,
            {"display": "DisplayStatus | null", "implied_stop_kind": "StopKind | null"},
        ),
        _enum("SESSION_STATUSES", "SessionStatus", vocab.SessionStatus),
        _group("LIVE_SESSION_STATUSES", "SessionStatus", vocab.LIVE),
        _group("UNFINISHED_SESSION_STATUSES", "SessionStatus", vocab.UNFINISHED),
        _group("ADVANCING_SESSION_STATUSES", "SessionStatus", vocab.ADVANCING),
        _group("AGENT_REPORTABLE_SESSION_STATUSES", "SessionStatus", vocab.AGENT_REPORTABLE),
        _group("CAP_SWEEP_LEAVES_SESSION_STATUSES", "SessionStatus", vocab.CAP_SWEEP_LEAVES),
        _group("COMMAND_FINISHED_SESSION_STATUSES", "SessionStatus", vocab.COMMAND_FINISHED),
        _group("UNREADABLE_EXIT_SESSION_STATUSES", "SessionStatus", vocab.UNREADABLE_EXIT),
        _traits("SESSION_TRAITS", "SessionStatus", vocab.SESSION_TRAITS, {}),
    ]
    return "\n".join(parts)


if __name__ == "__main__":
    if "--print" in sys.argv:
        sys.stdout.write(render())
    else:
        OUT.write_text(render())
        print(OUT.relative_to(OUT.parents[3]))
