"""The version and notes a hand-cut release computes from its merged PRs."""

from __future__ import annotations

import importlib.util
import json
import re
import sys
from pathlib import Path

import pytest

# `dev/` is not a package; plan_release imports next_tag as a sibling script.
_DEV = Path(__file__).resolve().parents[1] / "dev"
sys.path.insert(0, str(_DEV))
_SPEC = importlib.util.spec_from_file_location("plan_release", _DEV / "plan_release.py")
plan_release = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(plan_release)

_FIXTURES = Path(__file__).resolve().parent / "fixtures" / "release"


def pr(number, impact, body="", title="a title", highlight=False):
    labels = ["bug", f"release::{impact}"] + (["notes::highlight"] if highlight else [])
    return {"number": number, "title": title, "body": body, "labels": labels}


@pytest.mark.parametrize(
    ("impacts", "expected"),
    [
        (["minor", "minor", "patch", "patch", "patch"], "minor"),
        (["patch", "none"], "patch"),
        (["none", "major", "patch"], "major"),
        (["none", "none"], "none"),
        ([], "none"),
    ],
)
def test_the_largest_impact_wins(impacts, expected):
    assert plan_release.release_impact([pr(i, x) for i, x in enumerate(impacts)]) == expected


def test_an_unlabelled_pr_fails_the_release_by_number():
    with pytest.raises(ValueError, match="#7 has no release:: label"):
        unlabelled = {"number": 7, "title": "t", "body": "", "labels": []}
        plan_release.release_impact([pr(1, "patch"), unlabelled])


def test_changelog_section_is_the_entry():
    body = (
        "Why.\n\n## Changelog\n\n<!-- hint -->\nFix: the thing works.\n\n## Release impact\n\nstuff"
    )
    assert plan_release.changelog_entry(pr(12, "patch", body)) == "- Fix: the thing works. (#12)"


def test_every_bullet_of_a_group_carries_the_prs_number():
    """R10h-06: a ten-bullet group put `(#484)` on its last bullet alone. Each
    bullet at the margin gets it, at the end of its own text: after a wrapped
    line, ahead of a nested list."""
    body = (
        "## Changelog\n\n"
        "- Restart exits 1\n  with no server.\n"
        "- Disconnect is refused:\n"
        "  - while an item is open;\n"
        "  - paused ones included.\n"
        "* Doctor warns.\n"
    )
    assert plan_release.changelog_entry(pr(484, "patch", body)) == (
        "- Restart exits 1\n  with no server. (#484)\n"
        "- Disconnect is refused: (#484)\n"
        "  - while an item is open;\n"
        "  - paused ones included.\n"
        "* Doctor warns. (#484)"
    )


def test_a_fenced_example_is_never_numbered_and_every_list_style_is():
    """A line inside a code fence is an example, not a bullet; `+ ` and `1. `
    bullets at the margin are bullets as `- ` ones are."""
    body = (
        "## Changelog\n\n"
        "1. Restart exits 1.\n"
        "+ Connect asks first:\n"
        "  ```bash\n"
        "- not a bullet\n"
        "kraft repo connect\n"
        "  ```\n"
        "2. Disconnect is refused.\n"
    )
    assert plan_release.changelog_entry(pr(9, "patch", body)) == (
        "1. Restart exits 1. (#9)\n"
        "+ Connect asks first: (#9)\n"
        "  ```bash\n"
        "- not a bullet\n"
        "kraft repo connect\n"
        "  ```\n"
        "2. Disconnect is refused. (#9)"
    )


def test_a_changelog_last_in_the_body_leaves_its_footer_out():
    """A body ending in `## Changelog` carries the attribution, the session's
    link and a `---` footer after it: none of them is a change."""
    body = (
        "## Changelog\n\nFix: the thing works.\n\n"
        "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
        "https://claude.ai/code/session_01ABC\n\n"
        "---\n_Generated by [Claude Code](https://claude.ai/code)_\n"
    )
    assert plan_release.changelog_entry(pr(6, "patch", body)) == "- Fix: the thing works. (#6)"


def test_a_trailing_attribution_line_stays_out_of_the_entry():
    body = "## Changelog\n\nFix: the thing works.\n\n\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
    assert plan_release.changelog_entry(pr(5, "patch", body)) == "- Fix: the thing works. (#5)"


def test_no_changelog_section_falls_back_to_the_title():
    body = "## Changelog\n\n<!-- left empty -->\n"
    assert plan_release.changelog_entry(pr(3, "patch", body, title="fix: x")) == "- fix: x (#3)"


def test_notes_group_largest_first_and_skip_none():
    notes = plan_release.release_notes(
        [pr(1, "patch", title="p"), pr(2, "none", title="n"), pr(3, "minor", title="m")]
    )
    assert notes == "### New\n\n- m (#3)\n\n### Fixes\n\n- p (#1)\n"


def test_a_highlight_leads_the_notes_and_is_not_repeated():
    prs = [pr(1, "patch", title="p"), pr(2, "minor", title="m")]
    notes = plan_release.release_notes([*prs, pr(3, "minor", title="h", highlight=True)])
    assert notes == "### Highlights\n\n- h (#3)\n\n### New\n\n- m (#2)\n\n### Fixes\n\n- p (#1)\n"


def test_highlights_keep_pr_order_whatever_their_impact():
    prs = [
        pr(3, "patch", title="fix", highlight=True),
        pr(5, "minor", title="new"),
        pr(9, "major", title="break", highlight=True),
    ]
    assert plan_release.release_notes(prs).startswith(
        "### Highlights\n\n- fix (#3)\n\n- break (#9)\n\n### Breaking changes\n\n"
    )


def test_a_highlighted_major_stays_under_breaking_changes_too():
    prs = [pr(2, "major", title="old"), pr(9, "major", title="break", highlight=True)]
    assert plan_release.release_notes([*prs, pr(11, "patch", title="fix", highlight=True)]) == (
        "### Highlights\n\n- break (#9)\n\n- fix (#11)\n\n"
        "### Breaking changes\n\n- old (#2)\n\n- break (#9)\n"
    )


@pytest.mark.parametrize("label", ["Notes::Highlight", "notes::highlight ", "notes::higlight"])
def test_a_near_miss_notes_label_fails_the_release_by_number(label):
    near_miss = pr(4, "minor")
    near_miss["labels"].append(label)
    with pytest.raises(ValueError, match=f"#4 has the label {re.escape(repr(label))}"):
        plan_release.release_impact([pr(1, "patch"), near_miss])


def test_an_unlabelled_highlight_is_told_to_take_a_shipping_label():
    unlabelled = {"number": 7, "title": "t", "body": "", "labels": ["notes::highlight"]}
    with pytest.raises(ValueError, match="#7 has no release:: label.*not release::none"):
        plan_release.release_impact([unlabelled])


def test_a_highlight_still_counts_toward_the_bump():
    prs = [pr(1, "patch"), pr(2, "minor", highlight=True)]
    assert plan_release.release_impact(prs) == "minor"


def test_a_highlighted_release_none_pr_fails_the_release_by_number():
    prs = [pr(1, "patch"), pr(8, "none", highlight=True)]
    with pytest.raises(ValueError, match="#8 has notes::highlight but release::none"):
        plan_release.release_impact(prs)
    with pytest.raises(ValueError, match="#8 has notes::highlight but release::none"):
        plan_release.release_notes(prs)


def test_no_highlight_leaves_real_notes_byte_identical(tmp_path, capsys):
    """Ten PRs of the 1.5.0 candidates and the one that made the release 2.0,
    in the shape release.yml's jq writes, their bodies (as they stood then)
    abridged around a verbatim `## Changelog`, and the notes the pre-highlight
    code writes (since R10h-06, with the PR's number on every bullet of a
    group). The one `release::major` makes v1.4.0's next release v2.0.0."""
    notes = tmp_path / "notes.md"
    plan_release.main(["plan", "v1.4.0", str(_FIXTURES / "prs-2.0.0.json"), str(notes)])
    assert capsys.readouterr().out == "v2.0.0\n"
    assert notes.read_bytes() == (_FIXTURES / "notes-2.0.0.md").read_bytes()


def test_a_highlight_lifts_one_real_entry_out_of_new():
    prs = json.loads((_FIXTURES / "prs-2.0.0.json").read_text())
    before = plan_release.release_notes(prs)
    redesign = next(p for p in prs if p["number"] == 400)
    redesign["labels"].append("notes::highlight")
    entry = plan_release.changelog_entry(redesign)
    after = plan_release.release_notes(prs)
    assert after.startswith(f"### Highlights\n\n{entry}\n\n### Breaking changes\n\n")
    assert after.count(entry) == 1
    assert after.replace(f"### Highlights\n\n{entry}\n\n", "") == before.replace(f"\n\n{entry}", "")


_PRE = "This is a pre-release. Install it with"
_KEEP = (
    "using the Python you installed Kraft with and leaving out `[vector]` if you don't use "
    "vector search, then run `kraft admin restart` (or `kraft admin start` if Kraft isn't "
    "running). From 1.5.0rc14 on, "
)
_WHEEL = "https://github.com/itsOmidKarami/kraft/releases/download"
_VSIX = "The VS Code extension on the Marketplace stays at the last release"


@pytest.mark.parametrize(
    ("tag", "line"),
    [
        (
            "v1.5.0rc2",
            f'{_PRE} `uv tool install --force --python 3.13 "kraft-sdlc[vector]==1.5.0rc2"`, '
            f"{_KEEP}`kraft admin update --channel rc` installs it too, keeping both. "
            f"{_VSIX} until 1.5.0 ships: install the `kraft-1.5.0rc2.vsix` attached below with "
            "`code --install-extension kraft-1.5.0rc2.vsix`.",
        ),
        (
            "v1.5.0b1",
            f'{_PRE} `uv tool install --force --python 3.13 "kraft-sdlc[vector] @ '
            f'{_WHEEL}/v1.5.0b1/kraft_sdlc-1.5.0b1-py3-none-any.whl"`, '
            f"{_KEEP}`kraft admin update --channel beta` installs it too, keeping both. "
            f"{_VSIX} until 1.5.0 ships: install the `kraft-1.5.0b1.vsix` attached below with "
            "`code --install-extension kraft-1.5.0b1.vsix`.",
        ),
        (
            "v1.5.0a3",
            f'{_PRE} `uv tool install --force --python 3.13 "kraft-sdlc[vector] @ '
            f'{_WHEEL}/v1.5.0a3/kraft_sdlc-1.5.0a3-py3-none-any.whl"`, '
            f"{_KEEP}`kraft admin update --channel alpha` installs it too, keeping both. "
            f"{_VSIX} until 1.5.0 ships: install the `kraft-1.5.0a3.vsix` attached below with "
            "`code --install-extension kraft-1.5.0a3.vsix`.",
        ),
    ],
)
def test_a_pre_release_says_how_to_install_it_above_its_notes(tag, line):
    """Only an rc is on PyPI; a beta or alpha points at its release's own wheel."""
    notes = "### Highlights\n\n- the headline (#1)\n\n### Fixes\n\n- a fix (#2)\n"
    assert plan_release.release_body(tag, notes) == f"{line}\n\n{notes}"


@pytest.mark.parametrize("mark", ["rc", "b", "a"])
def test_a_pre_release_leads_with_the_install_that_keeps_vector_and_the_python(mark):
    """1.4's `kraft admin update` installs a new release without `[vector]` and
    on uv's default Python, which the upgrade notes warn about, so it may not
    be the first way the notes offer. The `uv` command that keeps both is, and
    `kraft admin update` follows, for the installs whose update keeps them."""
    body = plan_release.release_body(f"v2.0.0{mark}1", "- x (#1)\n")
    uv, update = body.index("`uv tool install"), body.index("`kraft admin update")
    assert uv < update
    assert '"kraft-sdlc[vector]' in body[uv:update] and "--python 3.13" in body[uv:update]
    assert "From 1.5.0rc14 on, `kraft admin update" in body


def test_a_new_majors_pre_release_says_the_marketplace_extension_is_read_only():
    """The extension needs the server's own major, so against 2.0.0rc1 the
    Marketplace's 1.x one only reads; against a minor's pre-release it works,
    and only the newer `.vsix` is offered."""
    major = plan_release.release_body("v2.0.0rc1", "")
    assert (
        f"{_VSIX} until 2.0.0 ships and is read-only against this one: install the "
        "`kraft-2.0.0rc1.vsix` attached below with `code --install-extension kraft-2.0.0rc1.vsix`."
    ) in major
    assert "read-only" not in plan_release.release_body("v2.1.0rc1", "")


def test_the_vsix_a_pre_release_names_is_the_one_release_yml_attaches():
    text = (_DEV.parent / ".github" / "workflows" / "release.yml").read_text()
    assert '--out "$RUNNER_TEMP/vsix/kraft-${TAG#v}.vsix"' in text
    assert "`kraft-2.0.0rc1.vsix`" in plan_release.release_body("v2.0.0rc1", "")


def test_the_wheel_a_pre_release_names_is_the_package_kraft_publishes():
    """The URL is built, not read off the release, so it must spell the wheel
    as `uv build` names `kraft-sdlc`'s: normalized, pure Python."""
    from kraft.update import PACKAGE

    body = plan_release.release_body("v2.0.0b1", "")
    assert f"/{PACKAGE.replace('-', '_')}-2.0.0b1-py3-none-any.whl" in body


def test_every_pre_release_channel_is_one_update_accepts():
    from kraft.update import CHANNELS

    for kind, mark in plan_release.PRE_MARKS.items():
        body = plan_release.release_body(f"v1.5.0{mark}1", "- x (#1)\n")
        assert f"`kraft admin update --channel {kind}`" in body
        assert kind in CHANNELS


@pytest.mark.parametrize("tag", ["v1.5.0", "1.5.0", "", "v1.5.0rc", "v1.5.0.rc1"])
def test_a_stable_release_body_is_its_notes_byte_for_byte(tmp_path, tag):
    """The real 2.0.0 notes, through the command release.yml runs."""
    notes, body = _FIXTURES / "notes-2.0.0.md", tmp_path / "body.md"
    plan_release.main(["body", tag, str(notes), str(body)])
    assert body.read_bytes() == notes.read_bytes()


def test_the_2_0_layout_tells_the_story_once():
    """2.0's notes: #400, a highlighted minor, carries the story and the
    upgrade notes at the top; the major PR that makes the release 2.0 is not
    highlighted, so its short entry sits alone under Breaking changes, and
    neither is printed twice (a highlighted major would be)."""
    prs = json.loads((_FIXTURES / "prs-2.0.0.json").read_text())
    redesign = next(p for p in prs if p["number"] == 400)
    redesign["labels"].append("notes::highlight")
    major = next(p for p in prs if "release::major" in p["labels"])
    story, breaking = map(plan_release.changelog_entry, (redesign, major))
    notes = plan_release.release_notes(prs)
    assert notes.startswith(
        f"### Highlights\n\n{story}\n\n### Breaking changes\n\n{breaking}\n\n### New\n\n"
    )
    assert notes.count(story) == notes.count(breaking) == 1
    assert plan_release.release_impact(prs) == "major"


def test_the_release_is_created_from_the_body_and_the_changelogs_from_the_notes():
    text = (_DEV.parent / ".github" / "workflows" / "release.yml").read_text()
    body = 'plan_release.py" body "$TAG" "$RUNNER_TEMP/notes.md" "$RUNNER_TEMP/body.md"'
    # After the pre-release tag is numbered, and before the dry run blanks it.
    assert text.index('plan_release.py" pre "$TAG"') < text.index(body)
    assert text.index(body) < text.index('cat "$RUNNER_TEMP/body.md"') < text.index("TAG=\n")
    assert '--notes-file "$RUNNER_TEMP/body.md"' in text
    assert text.count('"$RUNNER_TEMP/notes.md" CHANGELOG.md') == 1
    assert 'changelog "$VERSION" "$RUNNER_TEMP/notes.md"\n' in text


def test_changelog_goes_above_the_newest_section(tmp_path):
    path = tmp_path / "CHANGELOG.md"
    path.write_text("# Changelog\n\nPreamble.\n\n## 1.0.0\n\n- old\n")
    plan_release.write_changelog("1.1.0", "### New\n\n- new (#4)\n", path)
    assert path.read_text() == (
        "# Changelog\n\nPreamble.\n\n## 1.1.0\n\n### New\n\n- new (#4)\n\n## 1.0.0\n\n- old\n"
    )
    with pytest.raises(ValueError, match="already has"):
        plan_release.write_changelog("1.1.0", "- again\n", path)


def test_a_changelog_with_no_section_yet_gets_its_first(tmp_path):
    path = tmp_path / "CHANGELOG.md"
    path.write_text("# Changelog\n\nPreamble.\n")
    plan_release.write_changelog("1.1.0", "- new (#4)\n", path)
    assert path.read_text() == "# Changelog\n\nPreamble.\n\n## 1.1.0\n\n- new (#4)\n"
    plan_release.write_changelog("1.2.0", "- newer (#5)\n", path)
    assert path.read_text() == (
        "# Changelog\n\nPreamble.\n\n## 1.2.0\n\n- newer (#5)\n\n## 1.1.0\n\n- new (#4)\n"
    )


def test_the_changelog_command_writes_the_file_it_is_given(tmp_path):
    notes, extension = tmp_path / "notes.md", tmp_path / "vscode-CHANGELOG.md"
    notes.write_text("### Fixes\n\n- fixed (#9)\n")
    extension.write_text("# Changelog\n\nPreamble.\n")
    repository = plan_release.CHANGELOG.read_text()
    plan_release.main(["changelog", "9.9.9", str(notes), str(extension)])
    assert (
        extension.read_text()
        == "# Changelog\n\nPreamble.\n\n## 9.9.9\n\n### Fixes\n\n- fixed (#9)\n"
    )
    assert plan_release.CHANGELOG.read_text() == repository


def test_the_extension_changelog_takes_the_release_notes_the_way_the_root_one_does(tmp_path):
    root = Path(__file__).resolve().parents[1]
    path = tmp_path / "CHANGELOG.md"
    path.write_text((root / "vscode" / "CHANGELOG.md").read_text())
    plan_release.write_changelog("1.5.0", "### New\n\n- new (#4)\n", path)
    text = path.read_text()
    assert text.startswith("# Changelog\n\nNotable changes to the Kraft VS Code extension")
    # The newest section, above any the file already holds (2.0.0 was the first stamped).
    assert text[text.index("\n## ") :].startswith("\n## 1.5.0\n\n### New\n\n- new (#4)\n")
    assert "do not\nedit this file by hand" in text


def test_a_stable_release_body_keeps_crlf_notes_byte_for_byte(tmp_path):
    """A PR body written with CRLF line ends reaches the notes as CRLF."""
    notes, body = tmp_path / "notes.md", tmp_path / "body.md"
    notes.write_bytes(b"### Fixes\r\n\r\n- a fix (#2)\r\n")
    plan_release.main(["body", "v1.5.0", str(notes), str(body)])
    assert body.read_bytes() == notes.read_bytes()
