// Generated by dev/gen_vocab.py from kraft.vocab. Do not edit: run `just vocab`.

export const DISPLAY_STATUSES = ["archived", "done", "cancelled", "paused", "running", "waiting", "queued", "needs_you", "escalated", "failed"] as const;
export type DisplayStatus = (typeof DISPLAY_STATUSES)[number];

export const STOP_KINDS = ["gate", "question", "cap", "budget", "failed", "conflict", "mr_closed", "config", "infra", "stuck", "wait", "rate_limit"] as const;
export type StopKind = (typeof STOP_KINDS)[number];

export const FAILURE_STOP_KINDS: readonly StopKind[] = ["failed", "config", "infra"];

export const STOP_TRAITS: Record<StopKind, { status: string; stored: boolean; failure: boolean }> = {
  "gate": { status: "needs_human", stored: false, failure: false },
  "question": { status: "needs_human", stored: true, failure: false },
  "cap": { status: "needs_human", stored: true, failure: false },
  "budget": { status: "needs_human", stored: true, failure: false },
  "failed": { status: "needs_human", stored: true, failure: true },
  "conflict": { status: "needs_human", stored: true, failure: false },
  "mr_closed": { status: "needs_human", stored: true, failure: false },
  "config": { status: "needs_human", stored: true, failure: true },
  "infra": { status: "needs_human", stored: true, failure: true },
  "stuck": { status: "needs_human", stored: true, failure: false },
  "wait": { status: "waiting", stored: true, failure: false },
  "rate_limit": { status: "rate_limited", stored: true, failure: false },
};

export const WORK_ITEM_STATUSES = ["active", "needs_human", "completed", "paused", "abandoned", "rate_limited", "waiting", "queued"] as const;
export type WorkItemStatus = (typeof WORK_ITEM_STATUSES)[number];

export const ENDED_STATUSES: readonly WorkItemStatus[] = ["completed", "abandoned"];

export const STOPPED_STATUSES: readonly WorkItemStatus[] = ["needs_human", "rate_limited", "waiting"];

export const HOLDS_SLOT_STATUSES: readonly WorkItemStatus[] = ["active"];

export const RUNNING_STATUSES: readonly WorkItemStatus[] = ["active", "waiting"];

export const COMMANDS_MAY_START_STATUSES: readonly WorkItemStatus[] = ["active", "paused", "rate_limited", "waiting"];

export const MR_WATCHED_STATUSES: readonly WorkItemStatus[] = ["needs_human", "waiting"];

export const WORK_ITEM_TRAITS: Record<WorkItemStatus, { display: DisplayStatus | null; implied_stop_kind: StopKind | null; ended: boolean; stopped: boolean; holds_slot: boolean; running: boolean; commands_may_start: boolean; mr_watched: boolean }> = {
  "active": { display: "running", implied_stop_kind: null, ended: false, stopped: false, holds_slot: true, running: true, commands_may_start: true, mr_watched: false },
  "needs_human": { display: null, implied_stop_kind: null, ended: false, stopped: true, holds_slot: false, running: false, commands_may_start: false, mr_watched: true },
  "completed": { display: "done", implied_stop_kind: null, ended: true, stopped: false, holds_slot: false, running: false, commands_may_start: false, mr_watched: false },
  "paused": { display: "paused", implied_stop_kind: null, ended: false, stopped: false, holds_slot: false, running: false, commands_may_start: true, mr_watched: false },
  "abandoned": { display: "cancelled", implied_stop_kind: null, ended: true, stopped: false, holds_slot: false, running: false, commands_may_start: false, mr_watched: false },
  "rate_limited": { display: "waiting", implied_stop_kind: "rate_limit", ended: false, stopped: true, holds_slot: false, running: false, commands_may_start: true, mr_watched: false },
  "waiting": { display: "waiting", implied_stop_kind: "wait", ended: false, stopped: true, holds_slot: false, running: true, commands_may_start: true, mr_watched: true },
  "queued": { display: "queued", implied_stop_kind: null, ended: false, stopped: false, holds_slot: false, running: false, commands_may_start: false, mr_watched: false },
};

export const SESSION_STATUSES = ["pending", "running", "done", "failed", "capped_out", "paused", "unknown", "done_with_concerns", "needs_context", "rate_limited", "config_error", "waiting", "conflict", "infra", "infra_stop"] as const;
export type SessionStatus = (typeof SESSION_STATUSES)[number];

export const LIVE_SESSION_STATUSES: readonly SessionStatus[] = ["pending", "running"];

export const UNFINISHED_SESSION_STATUSES: readonly SessionStatus[] = ["pending", "running", "paused", "needs_context", "rate_limited", "waiting"];

export const ADVANCING_SESSION_STATUSES: readonly SessionStatus[] = ["done", "done_with_concerns"];

export const AGENT_REPORTABLE_SESSION_STATUSES: readonly SessionStatus[] = ["done", "failed", "done_with_concerns", "needs_context"];

export const CAP_SWEEP_LEAVES_SESSION_STATUSES: readonly SessionStatus[] = ["done", "capped_out", "done_with_concerns", "waiting"];

export const COMMAND_FINISHED_SESSION_STATUSES: readonly SessionStatus[] = ["done", "failed"];

export const UNREADABLE_EXIT_SESSION_STATUSES: readonly SessionStatus[] = ["failed", "unknown"];

export const SESSION_TRAITS: Record<SessionStatus, { live: boolean; unfinished: boolean; advancing: boolean; agent_reportable: boolean; cap_sweep_leaves: boolean; command_finished: boolean; unreadable_exit: boolean }> = {
  "pending": { live: true, unfinished: true, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "running": { live: true, unfinished: true, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "done": { live: false, unfinished: false, advancing: true, agent_reportable: true, cap_sweep_leaves: true, command_finished: true, unreadable_exit: false },
  "failed": { live: false, unfinished: false, advancing: false, agent_reportable: true, cap_sweep_leaves: false, command_finished: true, unreadable_exit: true },
  "capped_out": { live: false, unfinished: false, advancing: false, agent_reportable: false, cap_sweep_leaves: true, command_finished: false, unreadable_exit: false },
  "paused": { live: false, unfinished: true, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "unknown": { live: false, unfinished: false, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: true },
  "done_with_concerns": { live: false, unfinished: false, advancing: true, agent_reportable: true, cap_sweep_leaves: true, command_finished: false, unreadable_exit: false },
  "needs_context": { live: false, unfinished: true, advancing: false, agent_reportable: true, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "rate_limited": { live: false, unfinished: true, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "config_error": { live: false, unfinished: false, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "waiting": { live: false, unfinished: true, advancing: false, agent_reportable: false, cap_sweep_leaves: true, command_finished: false, unreadable_exit: false },
  "conflict": { live: false, unfinished: false, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "infra": { live: false, unfinished: false, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
  "infra_stop": { live: false, unfinished: false, advancing: false, agent_reportable: false, cap_sweep_leaves: false, command_finished: false, unreadable_exit: false },
};

export const WORK_ITEM_EVENTS = ["work_item_created", "work_item_attachments", "work_item_resumed", "pause_requested", "work_item_queued", "work_item_dequeued", "work_item_blocked_by_dependency", "paused_by_broken_base", "work_item_needs_human", "work_item_waiting", "work_item_rate_limited", "work_item_retried", "work_item_completed", "work_item_manually_completed", "work_item_cancelled", "work_item_abandoned", "work_item_archived", "work_item_restored", "work_item_title_edited", "work_item_description_edited", "plan_progress", "steer_context_set", "steer_undelivered"] as const;
export type WorkItemEvent = (typeof WORK_ITEM_EVENTS)[number];

export const CHAIN_EVENTS = ["chain_loaded", "worktree_prepared", "node_started", "node_completed", "node_skipped", "scope_skipped", "node_recovery_started", "run_forked", "base_change_restart", "worktree_rebase_verified", "read_only_violated", "fix_cycle_started", "fix_cycle_finished", "fix_cycle_refunded", "findings_measured", "test_scopes_selected", "judge_verdict", "sweep_failed", "sweep_left_out", "bead_not_filed", "beads_left_open"] as const;
export type ChainEvent = (typeof CHAIN_EVENTS)[number];

export const GATE_EVENTS = ["gate_requested", "gate_approved", "gate_rejected", "gate_reopened", "gate_auto_review_started", "gate_auto_review_skipped", "gate_auto_review_discarded", "chain_revision_shown", "chain_revision_unchanged", "chain_revised", "artifact_refused", "review_submitted", "thread_updated", "rewind_requested", "rewind_cancelled", "reply_agent_wrote", "reply_agent_skipped", "reply_agent_failed"] as const;
export type GateEvent = (typeof GATE_EVENTS)[number];

export const SESSION_EVENTS = ["worker_session_created", "worker_session_started", "worker_session_exited", "worker_session_paused", "agent_session_resumed", "session_reattached", "session_unknown", "background_jobs_abandoned", "permission_decision"] as const;
export type SessionEvent = (typeof SESSION_EVENTS)[number];

export const LIMIT_EVENTS = ["time_cap_reached", "scope_budget_reached", "budget_changed", "budget_raised", "spend_unpriced", "cap_counters_reset", "rate_limit_hit", "launch_fallback", "launch_fallback_exhausted"] as const;
export type LimitEvent = (typeof LIMIT_EVENTS)[number];

export const ESCALATION_EVENTS = ["escalation_message", "stuck_escalation_started", "stuck_escalation_finished", "work_item_auto_escalate_skipped", "work_item_auto_escalate_capped", "work_item_self_retry_requested", "work_item_self_retry_dropped"] as const;
export type EscalationEvent = (typeof ESCALATION_EVENTS)[number];

export const FORGE_EVENTS = ["mr_opened", "mr_closed", "mr_reopened", "mr_labels_set", "external_wait_started", "external_wait_observed", "external_wait_rebounded", "external_wait_ended", "ci_infra_exhausted", "ci_run_abandoned", "ci_not_configured", "automated_review_not_configured", "automated_review_errored"] as const;
export type ForgeEvent = (typeof FORGE_EVENTS)[number];

export const SANDBOX_EVENTS = ["sandbox_egress_refused", "sandbox_oom_killed", "sandbox_branch_not_synced", "sandbox_kit_resolved"] as const;
export type SandboxEvent = (typeof SANDBOX_EVENTS)[number];

export const SETTINGS_EVENTS = ["chain_template_changed", "attachments_changed", "agent_overrides_changed", "node_overrides_changed", "policy_override_changed", "notification_failed"] as const;
export type SettingsEvent = (typeof SETTINGS_EVENTS)[number];

export const EVENT_TYPES = [...WORK_ITEM_EVENTS, ...CHAIN_EVENTS, ...GATE_EVENTS, ...SESSION_EVENTS, ...LIMIT_EVENTS, ...ESCALATION_EVENTS, ...FORGE_EVENTS, ...SANDBOX_EVENTS, ...SETTINGS_EVENTS] as const;
export type EventType = (typeof EVENT_TYPES)[number];
